### ISSUE TITLE
Bild upload button

### ISSUE THREAD

**Issue by pr0user** [retropr0/pr0p0st#11]
evt ein Button zum Bild hochladen?
Viele verstehen das Drag n Drop Prinzip nicht

**Comment by retropr0** [comment]
Das mache ich nachher mal. Ich wollte eh noch die Position beim DnD festlegen, um nicht immer hochscrollen zu müssen, wenn man ein neues Bild reinzieht.

**Comment by retropr0** [comment]
Bisschen verspätet aber dafür gibt es zusätzlich das Positionieren eingefügter Bilder an der Mausposition. Per Button eingefügte Bilder werden an das Ende der Canvas gezeichnet.
