### ISSUE TITLE
Drag & Drop - Reference Error: event is not defined

### ISSUE THREAD

**Issue by CJuette** [retropr0/pr0p0st#4]
Wenn ich versuche nen Bild zu draggen und droppen wirft mir Firebug bei der Funktion 
`reader.onload = function (evt)`
nen Error "ReferenceError: event is not defined" raus. Das Bild wird dann nicht eingebunden.

**Comment by retropr0** [comment]
Scheint ein Problem mit dem Fokus zu sein. Klickt man vorher in die Canvas oder die Seite, funktioniert es. Gucke ich mir nachher mal an.

**Comment by retropr0** [comment]
Ich verzweifle gerade etwas an diesem Bug. Du bist nicht zufällig auch unter Linux unterwegs?

**Comment by CJuette** [comment]
Ne unter Windows momentan. Hab grad mal gebrancht und was geändert, und bei mir lokal funktioniert es jetzt..

**Comment by retropr0** [comment]
Ich lasse das hier vorerst mal offen, da ich es lokal unter Linux noch reproduzieren kann.

**Comment by retropr0** [comment]
Habe es bisher nicht wieder gesehen. Sollte da noch was sein, wieder öffnen.
