### ISSUE TITLE
Feature: Farbe User Ränge

### ISSUE THREAD

**Issue by pr0user** [retropr0/pr0p0st#7]
by quietmychild:
Ich moechte nicht gleich zu anspruchsvoll werden, aber wer noch die weiteren Farben der User-Raenge hinzufuegen koennte waere spitze.

**Comment by retropr0** [comment]
Ich frage mich zwar für welche Art von Post man das gebrauchen könnte aber das können wir machen.

**Comment by retropr0** [comment]
Done
